apiVersion: sim.k8s.io/v1
kind: NodeSimulator
metadata:
  name: nodesimulator-sample
spec:
  # Add fields here
  cpu: "1000"
  memory: "1000"
  prefix: "test"
  podNumber: "100"
  podCidr: "172.12.1.0/8"
  number: 1500
